apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres_clicks
    type: grafana-postgresql-datasource
    access: proxy
    url: urldb:5432
    database: url
    user: myuser
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400