name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      HOST: root@ssh.cloud.nstu.ru
      PORT: 5157
      DEPLOY_DIRECTORY: /root/apps/url-shortener
      CONFIG_PATH: /root/apps/url-shortener/config/config.yaml
      ENV_FILE_PATH: /root/apps/url-shortener/config.env
      STORAGE_HOST: urldb
      STORAGE_PORT: "5432"
      HTTP_SERVER_ADDRESS: url-shortener:8080
      SSO_ADDRESS: sso:44044

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Build app
        run: |
          go mod download
          go build -o url-shortener ./cmd/url-shortener
      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Remove old systemd service file
        run: |
          ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "rm -f /etc/systemd/system/url-shortener.service"
      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la ${{ github.workspace }}/deployment
      - name: Create environment file on server
        run: |
          ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          touch ${{ env.ENV_FILE_PATH }} && \
          chmod 600 ${{ env.ENV_FILE_PATH }} && \
          echo 'CONFIG_PATH=${{ env.CONFIG_PATH }}' > ${{ env.ENV_FILE_PATH }} && \
          echo 'ENV=prod' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'STORAGE_HOST=${{ env.STORAGE_HOST }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'STORAGE_PORT=${{ env.STORAGE_PORT }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'HTTP_SERVER_ADDRESS=${{ env.HTTP_SERVER_ADDRESS }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'SSO_ADDRESS=${{ env.SSO_ADDRESS }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'HTTP_SERVER_PASSWORD=${{ secrets.AUTH_PASS }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'APP_SECRET=${{ secrets.APP_SECRET }}' >> ${{ env.ENV_FILE_PATH }} "
      - name: Copy systemd service file
        run: |
          scp -i deploy_key.pem -P ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ github.workspace }}/deployment/url-shortener.service ${{ env.HOST }}:/tmp/url-shortener.service
          ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "mv /tmp/url-shortener.service /etc/systemd/system/url-shortener.service"
      - name: Start application
        run: |
          ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no ${{ env.HOST }} "systemctl daemon-reload && systemctl restart url-shortener.service"